import type { Metadata } from "next";
import Link from "next/link";
import data from "@/data/realworld-findings.json";
import type { FindingsReport, ReportContract, ReportMeasurement } from "@/lib/findings/report";
import { findingTitle } from "@/components/findingTitles";

export const metadata: Metadata = {
  title: "Findings — MonadLens",
  description: "MonadLens run over real, verified contracts: heuristic findings and measured contention.",
};

// Generated by `npx tsx scripts/realworld-check.ts --measure --json`; nothing here is typed in by hand.
const report = data as FindingsReport;


const GROUP_LABEL: Record<ReportContract["group"], string> = {
  real: "Real contract",
  synthetic: "Synthetic fixture",
  port: "Measurement-only port",
};

function Measurement({ m, note }: { m?: ReportMeasurement; note?: string }) {
  if (!m) return <p className="text-sm text-zinc-500">Not measured in this run.</p>;
  if (!m.measured) {
    return (
      <p className="text-sm text-zinc-400">
        <span className="font-medium text-zinc-300">Not measured</span> ({m.target}): {m.reason}
      </p>
    );
  }
  return (
    <div className="flex flex-col gap-1 text-sm">
      <p>
        <span className="rounded bg-emerald-500/15 px-1.5 py-0.5 text-xs font-medium text-emerald-300">Measured</span>{" "}
        <span className="font-mono text-zinc-300">{m.target}</span> × {m.txCount} txs from {m.txCount} senders:
        critical path <span className="font-semibold text-zinc-100">{m.criticalPathLength}</span> of {m.txCount},{" "}
        {m.reExecutionCount} re-executions, avg gas {m.avgGasUsed.toLocaleString("en-US")}.
      </p>
      {note && <p className="text-xs text-zinc-500">{note}</p>}
      {m.hotSlots.length > 0 && (
        <ul className="mt-1 flex flex-col gap-0.5 font-mono text-xs">
          {m.hotSlots.map((h) => (
            <li key={h.label} className="text-zinc-300">
              hot <span className="text-zinc-100">{h.label}</span>: {h.writers} write, {h.readers} read{" "}
              {h.predicted ? (
                <span className="font-sans text-emerald-300">· predicted by a static rule</span>
              ) : (
                <span className="font-sans text-amber-300">· not caught by static rules</span>
              )}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function ContractCard({ c }: { c: ReportContract }) {
  return (
    <section className="contract-card">
      <div className="contract-top">
        <div className="min-w-0">
          <h3 className="contract-name">{c.file}</h3>
          <p className="muted small">
            {GROUP_LABEL[c.group]}
            {c.sourceUrl && (
              <>
                {" · "}
                <a href={c.sourceUrl} className="text-link small" target="_blank" rel="noreferrer">
                  source
                </a>
              </>
            )}
            {c.license && ` · ${c.license.split(/ \(|\. |;/)[0].trim()}`}
          </p>
        </div>
        <div className="contract-score">
          <div className="block-title">Heuristic score</div>
          <div className="score-value">{c.score ?? "—"}</div>
        </div>
      </div>

      <div className="measured-head">
        <span className="tag tag-static">
          {c.findings.length} static finding{c.findings.length === 1 ? "" : "s"}
        </span>
        {c.measurement?.measured ? (
          <span className="tag tag-measured">Measured</span>
        ) : (
          <span className="tag tag-static">Not measured</span>
        )}
      </div>
      <details className="disclosure">
        <summary>Inspect</summary>
        <div className="disclosure-content">
          {(c.crashed || c.parseError) && (
            <p role="alert" className="note note-warn">
              {c.crashed ? "Analyzer crashed." : `Parse error: ${c.parseError}`}
            </p>
          )}

          {c.findings.length === 0 ? (
            <p className="muted">No static findings.</p>
          ) : (
            <ul className="flex flex-col gap-3">
              {c.findings.map((f, i) => (
                <li key={`${f.ruleId}-${f.line}-${i}`} className="flex flex-col gap-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className={`sev sev-${f.severity}`}>{f.severity}</span>
                    <span className="font-medium text-zinc-100">{findingTitle(f.ruleId)}</span>
                    <span className="mono muted small">
                      {f.ruleId} · line {f.line}
                      {f.variable ? ` · ${f.variable}` : ""}
                    </span>
                  </div>
                  <p className="text-sm text-zinc-300">{f.message}</p>
                </li>
              ))}
            </ul>
          )}

          <Measurement m={c.measurement} note={c.measurementNote} />
        </div>
      </details>
    </section>
  );
}

export default function FindingsPage() {
  const validation = report.contracts.filter((c) => c.group !== "port");
  const crashes = validation.filter((c) => c.crashed).length;
  const parseErrors = validation.filter((c) => c.parseError).length;
  const missed = report.contracts.flatMap((c) =>
    c.measurement?.measured ? c.measurement.hotSlots.filter((h) => !h.predicted).map((h) => ({ c, h })) : []
  );

  return (
    <div className="app-root">
      <header className="topbar page-header">
        <Link href="/" className="topbar-brand" aria-label="MonadLens, home">
          <span className="wordmark-sm">
            Monad<span>Lens</span>
          </span>
        </Link>
        <Link href="/#workspace" className="btn btn-primary btn-sm">
          Test your contract
        </Link>
      </header>

      <div className="page-hero">
        <p className="eyebrow">Validation</p>
        <h1>Findings on real contracts</h1>
        <div className="page-stats">
          <span className="stat">
            <strong>{validation.length}</strong>contracts
          </span>
          <span className="stat">
            <strong>{crashes}</strong>crashes
          </span>
          <span className="stat">
            <strong>{parseErrors}</strong>parse errors
          </span>
        </div>
        <details className="disclosure mt-4">
          <summary>About this run</summary>
          <p className="max-w-2xl py-2 text-sm">
            Run {report.generatedAt}. Scores are heuristic. Measured numbers come from 100 transactions in one local
            Anvil block. Contracts requiring an older compiler are not measured.
          </p>
        </details>
      </div>

      <main className="page-main">
        {missed.length > 0 && (
          <section className="contract-card" style={{ borderColor: "rgba(245,197,107,0.3)" }}>
            <h2 className="text-base font-semibold text-amber-200">Static rules missed it, measurement caught it</h2>
            <details className="disclosure">
              <summary>Inspect</summary>
              <div className="disclosure-content">
                {missed.map(({ c, h }) => (
                  <p key={`${c.file}-${h.label}`} className="text-sm text-zinc-300">
                    <span className="mono">{c.file}</span>: <span className="mono text-zinc-100">{h.label}</span> is hot
                    in the measured block ({h.writers} write, {h.readers} read), but no static finding names it.
                    {c.measurementNote && <span className="text-zinc-400"> {c.measurementNote}</span>}
                  </p>
                ))}
              </div>
            </details>
          </section>
        )}

        <h2 className="section-label">Validation contracts</h2>
        {validation.map((c) => (
          <ContractCard key={c.file} c={c} />
        ))}

        {report.contracts.some((c) => c.group === "port") && (
          <>
            <h2 className="section-label">Measurement-only ports</h2>
            {report.contracts
              .filter((c) => c.group === "port")
              .map((c) => (
                <ContractCard key={c.file} c={c} />
              ))}
          </>
        )}
      </main>
    </div>
  );
}
