import type { Metadata } from "next";
import Link from "next/link";
import data from "@/data/realworld-findings.json";
import type { FindingsReport, ReportContract, ReportMeasurement } from "@/lib/findings/report";

export const metadata: Metadata = {
  title: "Findings — MonadLens",
  description: "MonadLens run over real, verified contracts: heuristic findings and measured contention.",
};

// Generated by `npx tsx scripts/realworld-check.ts --measure --json`; nothing here is typed in by hand.
const report = data as FindingsReport;

const SEVERITY_COLOR: Record<string, string> = {
  critical: "text-red-400",
  high: "text-orange-400",
  medium: "text-yellow-400",
  info: "text-purple-300",
  safe: "text-emerald-400",
};

const GROUP_LABEL: Record<ReportContract["group"], string> = {
  real: "Real contract",
  synthetic: "Synthetic fixture",
  port: "Measurement-only port",
};

function Measurement({ m, note }: { m?: ReportMeasurement; note?: string }) {
  if (!m) return <p className="text-sm text-zinc-500">Not measured in this run.</p>;
  if (!m.measured) {
    return (
      <p className="text-sm text-zinc-400">
        <span className="font-medium text-zinc-300">Not measured</span> ({m.target}): {m.reason}
      </p>
    );
  }
  return (
    <div className="flex flex-col gap-1 text-sm">
      <p>
        <span className="rounded bg-emerald-500/15 px-1.5 py-0.5 text-xs font-medium text-emerald-300">Measured</span>{" "}
        <span className="font-mono text-zinc-300">{m.target}</span> × {m.txCount} txs from {m.txCount} senders:
        critical path <span className="font-semibold text-zinc-100">{m.criticalPathLength}</span> of {m.txCount},{" "}
        {m.reExecutionCount} re-executions, avg gas {m.avgGasUsed.toLocaleString("en-US")}.
      </p>
      {note && <p className="text-xs text-zinc-500">{note}</p>}
      {m.hotSlots.length > 0 && (
        <ul className="mt-1 flex flex-col gap-0.5 font-mono text-xs">
          {m.hotSlots.map((h) => (
            <li key={h.label} className="text-zinc-300">
              hot <span className="text-zinc-100">{h.label}</span>: {h.writers} write, {h.readers} read{" "}
              {h.predicted ? (
                <span className="font-sans text-emerald-300">· predicted by a static rule</span>
              ) : (
                <span className="font-sans text-amber-300">· not caught by static rules</span>
              )}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function ContractCard({ c }: { c: ReportContract }) {
  return (
    <section className="flex flex-col gap-3 rounded-lg border border-purple-500/20 bg-[#13111C]/80 p-4">
      <div className="flex flex-wrap items-baseline justify-between gap-2">
        <div>
          <h3 className="font-mono text-sm font-semibold text-zinc-100">{c.file}</h3>
          <p className="text-xs text-zinc-500">
            {GROUP_LABEL[c.group]}
            {c.sourceUrl && (
              <>
                {" · "}
                <a href={c.sourceUrl} className="text-[#836EF9] hover:underline" target="_blank" rel="noreferrer">
                  source
                </a>
              </>
            )}
            {c.license && ` · ${c.license.split(/ \(|\. |;/)[0].trim()}`}
          </p>
        </div>
        <div className="text-right">
          <div className="text-xs uppercase tracking-wide text-zinc-500">Heuristic score</div>
          <div className="text-xl font-semibold text-[#836EF9]">{c.score ?? "—"}</div>
        </div>
      </div>

      {(c.crashed || c.parseError) && (
        <p className="text-sm text-red-400">{c.crashed ? "Analyzer crashed." : `Parse error: ${c.parseError}`}</p>
      )}

      {c.findings.length === 0 ? (
        <p className="text-sm text-zinc-500">No static findings.</p>
      ) : (
        <ul className="flex flex-col gap-1 text-sm">
          {c.findings.map((f, i) => (
            <li key={`${f.ruleId}-${f.line}-${i}`}>
              <span className={`font-mono text-xs ${SEVERITY_COLOR[f.severity] ?? ""}`}>
                {f.ruleId} · {f.severity} · line {f.line}
              </span>
              {f.variable && <span className="font-mono text-xs text-zinc-400"> · {f.variable}</span>}
              <p className="text-zinc-300">{f.message}</p>
            </li>
          ))}
        </ul>
      )}

      <Measurement m={c.measurement} note={c.measurementNote} />
    </section>
  );
}

export default function FindingsPage() {
  const validation = report.contracts.filter((c) => c.group !== "port");
  const crashes = validation.filter((c) => c.crashed).length;
  const parseErrors = validation.filter((c) => c.parseError).length;
  const missed = report.contracts.flatMap((c) =>
    c.measurement?.measured ? c.measurement.hotSlots.filter((h) => !h.predicted).map((h) => ({ c, h })) : []
  );

  return (
    <div className="flex flex-1 flex-col bg-[#0B0B0E] text-zinc-100">
      <header className="border-b border-purple-500/20 bg-[#13111C]/80 px-6 py-4">
        <Link href="/" className="text-sm text-zinc-400 hover:text-zinc-200">
          ← Monad<span className="text-[#836EF9]">Lens</span>
        </Link>
        <h1 className="mt-1 text-lg font-semibold">Findings on real contracts</h1>
        <p className="text-sm text-zinc-400">
          {validation.length} contracts, {crashes} crashes, {parseErrors} parse errors · run {report.generatedAt}. Scores
          are heuristic; measured numbers come from 100 transactions from distinct senders mined into one block on a local
          anvil. Contracts that need an older compiler are not measured.
        </p>
      </header>

      <main className="mx-auto flex w-full max-w-4xl flex-col gap-6 p-6">
        {missed.length > 0 && (
          <section className="flex flex-col gap-2 rounded-lg border border-amber-500/30 bg-amber-500/5 p-4">
            <h2 className="text-sm font-semibold text-amber-200">Static rules missed it, measurement caught it</h2>
            {missed.map(({ c, h }) => (
              <p key={`${c.file}-${h.label}`} className="text-sm text-zinc-300">
                <span className="font-mono">{c.file}</span>: <span className="font-mono text-zinc-100">{h.label}</span> is hot
                in the measured block ({h.writers} write, {h.readers} read), but no static finding names it.
                {c.measurementNote && <span className="text-zinc-500"> {c.measurementNote}</span>}
              </p>
            ))}
          </section>
        )}

        <h2 className="text-xs uppercase tracking-wide text-zinc-500">Validation contracts</h2>
        {validation.map((c) => (
          <ContractCard key={c.file} c={c} />
        ))}

        {report.contracts.some((c) => c.group === "port") && (
          <>
            <h2 className="text-xs uppercase tracking-wide text-zinc-500">Measurement-only ports</h2>
            {report.contracts
              .filter((c) => c.group === "port")
              .map((c) => (
                <ContractCard key={c.file} c={c} />
              ))}
          </>
        )}
      </main>
    </div>
  );
}
